# Generated by Django 2.1.7 on 2019-02-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_constructor', '0002_auto_20190227_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_constructor.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderingredient',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_constructor.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderingredient',
            unique_together={('order', 'ingredient')},
        ),
    ]
