# Generated by Django 2.1.7 on 2019-02-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_constructor', '0003_auto_20190228_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
