# Generated by Django 2.1.7 on 2019-02-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_constructor', '0006_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Ваш email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Ваш номер телефона'),
        ),
    ]
