# Generated by Django 2.1.7 on 2019-02-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_constructor', '0007_auto_20190228_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirmed',
        ),
    ]
